# -*- coding: utf-8 -*-
"""8queens_genetic_algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBPyKuE41CYlx3fRZHh_PmbTTZlj_Meu
"""

import random
N = 8
POP_SIZE = 8
MAX_GENERATIONS = 1000
MUTATION_RATE = 0.1
MAX_PAIRS = N * (N - 1) // 2

"""## 2. Make a random board

##Your task : Complete the **fitness** function
"""

def random_individual():
    return [random.randint(1, N) for _ in range(N)]

def fitness(board):
    non_attacking = 0
    attack=0
    
    for i in range(N):
        for j in range(i + 1, N):
            # TODO
            if board[i]==board[j]:
                attack = attack + 1
                
            if (abs(board[i]-board[j]) == abs(i-j)):
                attack +=1
                
    non_attacking = MAX_PAIRS-attack       
    return non_attacking

"""## 3. Selection — roulette wheel"""

def select_parent(population):
    scores = [fitness(b) for b in population]
    total = sum(scores)
    pick = random.uniform(0, total)
    running = 0
    for board, score in zip(population, scores):
        running += score
        if running >= pick:
            return board
    return population[-1]

"""## 4. Crossover and mutation"""

def crossover(parent1, parent2):
    point = random.randint(1, N - 1)
    child1 = parent1[:point] + parent2[point:]
    child2 = parent2[:point] + parent1[point:]
    return child1, child2

def mutate(board):
    column = random.randint(0, N - 1)
    board[column] = random.randint(1, N)
    return board

"""## 5. The Genetic Algorithm loop"""

def genetic_algorithm():
    population = [random_individual() for _ in range(POP_SIZE)]
    best = max(population, key=fitness)

    for generation in range(MAX_GENERATIONS):
        population.sort(key=fitness, reverse=True)
        new_population = [population[0]]

        while len(new_population) < POP_SIZE:
            p1 = select_parent(population)
            p2 = select_parent(population)
            c1, c2 = crossover(p1, p2)
            if random.random() < MUTATION_RATE:
                c1 = mutate(c1)
            if random.random() < MUTATION_RATE:
                c2 = mutate(c2)
            new_population.append(c1)
            if len(new_population) < POP_SIZE:
                new_population.append(c2)

        population = new_population
        current_best = max(population, key=fitness)
        if fitness(current_best) > fitness(best):
            best = current_best

        if fitness(best) == MAX_PAIRS:
            print("Solution found in generation", generation)
            break

    return best

"""## 6. Run it"""

solution = genetic_algorithm()
print("Best board:", solution)
print("Non-attacking pairs:", fitness(solution), "out of", MAX_PAIRS)

"""## 7. See the board as a grid"""

def print_board(board):
    for row in range(N, 0, -1):
        line = ""
        for col in range(N):
            line += " Q" if board[col] == row else " ."
        print(line)
    print()

print_board(solution)

"""## 8. Your task : Write the **two-point crossover** function
```
Parent A : [a1 | a2 a3 a4 | a5 a6 a7 a8]
Parent B : [b1 | b2 b3 b4 | b5 b6 b7 b8]   cuts after position 1 and after position 4
Child 1  : [a1 | b2 b3 b4 | a5 a6 a7 a8]  
Child 2  : [b1 | a2 a3 a4 | b5 b6 b7 b8]   
```

**Rules:**
1. Pick `point1` randomly between `1` and `N-2`.
2. Pick `point2` randomly **after** `point1` (from `point1 + 1` up to `N-1`) — the second cut must always come after the first.
3. Build the two children by keeping the outer parts of one parent and the middle of the other.

Fill in the four lines marked `TODO`, then run the test cell.
"""

def crossover_two_point(parent1, parent2):
    point1 = random.randint(1, N-2)   # TODO
    point2 = random.randint(point1+1, N-1)   # TODO

    child1 = parent1[:point1]+parent2[point1:point2]+parent1[point2:]  # TODO
    child2 = parent2[:point1]+parent1[point1:point2]+parent2[point2:]  # TODO
    return child1, child2

"""**Test your function.**"""

a = [1, 1, 1, 1, 1, 1, 1, 1]
b = [8, 8, 8, 8, 8, 8, 8, 8]

c1, c2 = crossover_two_point(a, b)
print("Child 1:", c1)
print("Child 2:", c2)